name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - development
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - development
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    env:
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}} 
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}} 
      AZURE_STATIC_WEB_APPS_API_TOKEN: ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN}}
      AZURE_STATIC_WEB_APPS_APP_NAME: ${{secrets.AZURE_STATIC_WEB_APPS_APP_NAME}}
      AZURE_STATIC_WEB_APPS_RESOURCE_GROUP: ${{secrets.AZURE_STATIC_WEB_APPS_RESOURCE_GROUP}}
      AZURE_STATIC_WEB_APPS_SUBSCRIPTION_ID: ${{secrets.AZURE_STATIC_WEB_APPS_SUBSCRIPTION_ID}}      
      DEPLOYMENT_ENVIRONMENT: ${{ github.ref_name == 'master' && 'production' || github.ref_name == 'development' && 'development' }}
      APP_LOCATION: "src"
      OUTPUT_LOCATION: "dist/gita-app/browser"
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        lfs: false

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Install Azure Static Web Apps CLI
      run: npm install -g @azure/static-web-apps-cli

    - name: Build project
      run: npm run build -- --configuration=${{ github.ref_name == 'master' && 'production' || 'development' }}
    
    - name: Deploy Static Web App
      run: |
        swa deploy \
          --app-location src \
          --output-location dist/gita-app/browser \
          --env $DEPLOYMENT_ENVIRONMENT \
          --deployment-token $AZURE_STATIC_WEB_APPS_API_TOKEN \
          --app-name $AZURE_STATIC_WEB_APPS_APP_NAME